# 设置访问的端口号
server:
  port: 80

# 添加配置延迟devtools等待时间
spring:
  devtools:
    restart:
      poll-interval: 5000


  application:
    name: cloud-consumer-order

# 配置eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka/
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/

