# 端口号
server:
  port: 8001

spring:
  # 应用名
  application:
    name: cloud-provider-payment


  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

    # 取消testWhileIdle is true, validationQuery not set报错
    druid:
      test-while-idle: true
      validation-query: SELECT 1

  # 添加配置延迟devtools等待时间
  devtools:
    restart:
      poll-interval: 5000



mybatis:
  # mybatis xml 文件地址
  mapper-locations: classpath:mapper/*.xml
  # 所有Entity别名类所在包
  type-aliases-package: com.lr.springcloud.entities



